---
title: "contour plot"
output:
  pdf_document: default
  html_document: default
---
```{r,include=FALSE}
# Read libraries
library(tidyverse)
library(ggplot2)
library(rcompanion)
library(viridis)
library(readxl)
```




```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_1_1<-subset(BF,Grid=="R1.29"&Time=="1")
BF_1_2<-subset(BF,Grid=="R1.29"&Time=="2")
BF_1_3<-subset(BF,Grid=="R1.29"&Time=="3")
BF_1_4<-subset(BF,Grid=="R1.29"&Time=="4")
BF_1_5<-subset(BF,Grid=="R1.29"&Time=="5")
BF_1_6<-subset(BF,Grid=="R1.29"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_1_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_1_1,aes(xaxis,yaxis,size=factor(Popud),color=factor(Popud)))+
  labs(title="Bacteria-feeding nematode population in Grid 1.29 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_1_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_1_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_1_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_1_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_1_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.29 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_2_1<-subset(BF,Grid=="R1.18"&Time=="1")
BF_2_2<-subset(BF,Grid=="R1.18"&Time=="2")
BF_2_3<-subset(BF,Grid=="R1.18"&Time=="3")
BF_2_4<-subset(BF,Grid=="R1.18"&Time=="4")
BF_2_5<-subset(BF,Grid=="R1.18"&Time=="5")
BF_2_6<-subset(BF,Grid=="R1.18"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_2_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(BF_2_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(BF_2_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_2_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_2_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_2_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.18 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_3_1<-subset(BF,Grid=="R1.13"&Time=="1")
BF_3_2<-subset(BF,Grid=="R1.13"&Time=="2")
BF_3_3<-subset(BF,Grid=="R1.13"&Time=="3")
BF_3_4<-subset(BF,Grid=="R1.13"&Time=="4")
BF_3_5<-subset(BF,Grid=="R1.13"&Time=="5")
BF_3_6<-subset(BF,Grid=="R1.13"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_3_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.13 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(BF_3_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.13 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(BF_3_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.13 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(BF_3_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.13 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_3_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.13 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_3_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.13 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_4_1<-subset(BF,Grid=="R1.09"&Time=="1")
BF_4_2<-subset(BF,Grid=="R1.09"&Time=="2")
BF_4_3<-subset(BF,Grid=="R1.09"&Time=="3")
BF_4_4<-subset(BF,Grid=="R1.09"&Time=="4")
BF_4_5<-subset(BF,Grid=="R1.09"&Time=="5")
BF_4_6<-subset(BF,Grid=="R1.09"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_4_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
    labs(title="Bacteria-feeding nematode in Grid 1.09 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_4_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.09 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_4_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.09 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_4_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.09 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_4_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.09 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_4_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.09 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_5_1<-subset(BF,Grid=="R1.02"&Time=="1")
BF_5_2<-subset(BF,Grid=="R1.02"&Time=="2")
BF_5_3<-subset(BF,Grid=="R1.02"&Time=="3")
BF_5_4<-subset(BF,Grid=="R1.02"&Time=="4")
BF_5_5<-subset(BF,Grid=="R1.02"&Time=="5")
BF_5_6<-subset(BF,Grid=="R1.02"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_5_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_5_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_5_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_5_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_5_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```



```{r,include=TRUE}

ggplot(BF_5_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 1.02 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```



```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_6_1<-subset(BF,Grid=="R0.92"&Time=="1")
BF_6_2<-subset(BF,Grid=="R0.92"&Time=="2")
BF_6_3<-subset(BF,Grid=="R0.92"&Time=="3")
BF_6_4<-subset(BF,Grid=="R0.92"&Time=="4")
BF_6_5<-subset(BF,Grid=="R0.92"&Time=="5")
BF_6_6<-subset(BF,Grid=="R0.92"&Time=="6")
```


```{r,include=TRUE}

ggplot(BF_6_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_6_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_6_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_6_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_6_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_6_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.92 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_7_1<-subset(BF,Grid=="R0.86"&Time=="1")
BF_7_2<-subset(BF,Grid=="R0.86"&Time=="2")
BF_7_3<-subset(BF,Grid=="R0.86"&Time=="3")
BF_7_4<-subset(BF,Grid=="R0.86"&Time=="4")
BF_7_5<-subset(BF,Grid=="R0.86"&Time=="5")
BF_7_6<-subset(BF,Grid=="R0.86"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_7_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_7_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_7_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_7_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_7_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_7_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.86 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```



```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_8_1<-subset(BF,Grid=="R0.77"&Time=="1")
BF_8_2<-subset(BF,Grid=="R0.77"&Time=="2")
BF_8_3<-subset(BF,Grid=="R0.77"&Time=="3")
BF_8_4<-subset(BF,Grid=="R0.77"&Time=="4")
BF_8_5<-subset(BF,Grid=="R0.77"&Time=="5")
BF_8_6<-subset(BF,Grid=="R0.77"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_8_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_8_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_8_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_8_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_8_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_8_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.77 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_9_1<-subset(BF,Grid=="R0.72"&Time=="1")
BF_9_2<-subset(BF,Grid=="R0.72"&Time=="2")
BF_9_3<-subset(BF,Grid=="R0.72"&Time=="3")
BF_9_4<-subset(BF,Grid=="R0.72"&Time=="4")
BF_9_5<-subset(BF,Grid=="R0.72"&Time=="5")
BF_9_6<-subset(BF,Grid=="R0.72"&Time=="6")
```


```{r,include=TRUE}

ggplot(BF_9_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_9_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_9_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```



```{r,include=TRUE}

ggplot(BF_9_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_9_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_9_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.72 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}
#transform the data
BF$Abd_T= transformTukey(BF$Abd,plotit = FALSE)
BF_10_1<-subset(BF,Grid=="R0.6"&Time=="1")
BF_10_2<-subset(BF,Grid=="R0.6"&Time=="2")
BF_10_3<-subset(BF,Grid=="R0.6"&Time=="3")
BF_10_4<-subset(BF,Grid=="R0.6"&Time=="4")
BF_10_5<-subset(BF,Grid=="R0.6"&Time=="5")
BF_10_6<-subset(BF,Grid=="R0.6"&Time=="6")
```

```{r,include=TRUE}

ggplot(BF_10_1,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 1st sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_10_2,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 2nd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_10_3,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 3rd sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}

ggplot(BF_10_4,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 4th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_10_5,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 5th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(BF_10_6,aes(xaxis,yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Bacteria-feeding nematode in Grid 0.6 at 6th sampling time")+
   scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```