---
title: "PFTemChan"
output: html_document
---

```{r,include=FALSE}
# Read libraries
library(readxl)
library(ggplot2)
library(MASS)
library(tidyverse)
library(rcompanion)
library(psych)
library(lmtest)
library(boot)
library(viridis)
```

##negative binomial regression model for plant feeders
```{r , echo=FALSE}
PFDM=glm(DIFU~Grid*Time,data=PF)
summary(PFDM)

```


```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_1_1<-subset(PF,Grid=="R1.29"&Time=="1")
PF_1_2<-subset(PF,Grid=="R1.29"&Time=="2")
PF_1_3<-subset(PF,Grid=="R1.29"&Time=="3")
PF_1_4<-subset(PF,Grid=="R1.29"&Time=="4")
PF_1_5<-subset(PF,Grid=="R1.29"&Time=="5")
PF_1_6<-subset(PF,Grid=="R1.29"&Time=="6")
```


```{r,include=TRUE}

ggplot(PF_1_1,aes(Xaxis,Yaxis,size=factor(Abd),color=factor(Abd)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_1_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_1_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(PF_1_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}

ggplot(PF_1_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_1_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.29 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_2_1<-subset(PF,Grid=="R1.18"&Time=="1")
PF_2_2<-subset(PF,Grid=="R1.18"&Time=="2")
PF_2_3<-subset(PF,Grid=="R1.18"&Time=="3")
PF_2_4<-subset(PF,Grid=="R1.18"&Time=="4")
PF_2_5<-subset(PF,Grid=="R1.18"&Time=="5")
PF_2_6<-subset(PF,Grid=="R1.18"&Time=="6")
```

```{r,include=TRUE}

ggplot(PF_2_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_2_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_2_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}

ggplot(PF_2_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_2_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_2_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.18 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_3_1<-subset(PF,Grid=="R1.13"&Time=="1")
PF_3_2<-subset(PF,Grid=="R1.13"&Time=="2")
PF_3_3<-subset(PF,Grid=="R1.13"&Time=="3")
PF_3_4<-subset(PF,Grid=="R1.13"&Time=="4")
PF_3_5<-subset(PF,Grid=="R1.13"&Time=="5")
PF_3_6<-subset(PF,Grid=="R1.13"&Time=="6")
```
```{r,include=TRUE}
ggplot(PF_3_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_3_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}
ggplot(PF_3_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_3_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_3_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_3_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.13 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_4_1<-subset(PF,Grid=="R1.09"&Time=="1")
PF_4_2<-subset(PF,Grid=="R1.09"&Time=="2")
PF_4_3<-subset(PF,Grid=="R1.09"&Time=="3")
PF_4_4<-subset(PF,Grid=="R1.09"&Time=="4")
PF_4_5<-subset(PF,Grid=="R1.09"&Time=="5")
PF_4_6<-subset(PF,Grid=="R1.09"&Time=="6")
```

```{r,include=TRUE}
ggplot(PF_4_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_4_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_4_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_4_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_4_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_4_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.09 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_5_1<-subset(PF,Grid=="R1.02"&Time=="1")
PF_5_2<-subset(PF,Grid=="R1.02"&Time=="2")
PF_5_3<-subset(PF,Grid=="R1.02"&Time=="3")
PF_5_4<-subset(PF,Grid=="R1.02"&Time=="4")
PF_5_5<-subset(PF,Grid=="R1.02"&Time=="5")
PF_5_6<-subset(PF,Grid=="R1.02"&Time=="6")
```
```{r,include=TRUE}
ggplot(PF_5_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_5_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_5_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_5_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_5_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_5_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 1.02 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_6_1<-subset(PF,Grid=="R0.92"&Time=="1")
PF_6_2<-subset(PF,Grid=="R0.92"&Time=="2")
PF_6_3<-subset(PF,Grid=="R0.92"&Time=="3")
PF_6_4<-subset(PF,Grid=="R0.92"&Time=="4")
PF_6_5<-subset(PF,Grid=="R0.92"&Time=="5")
PF_6_6<-subset(PF,Grid=="R0.92"&Time=="6")
```

```{r,include=TRUE}
ggplot(PF_6_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_6_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_6_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_6_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_6_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_6_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.92 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_7_1<-subset(PF,Grid=="R0.86"&Time=="1")
PF_7_2<-subset(PF,Grid=="R0.86"&Time=="2")
PF_7_3<-subset(PF,Grid=="R0.86"&Time=="3")
PF_7_4<-subset(PF,Grid=="R0.86"&Time=="4")
PF_7_5<-subset(PF,Grid=="R0.86"&Time=="5")
PF_7_6<-subset(PF,Grid=="R0.86"&Time=="6")
```

```{r,include=TRUE}
ggplot(PF_7_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r,include=TRUE}
ggplot(PF_7_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_7_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_7_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_7_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_7_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.86 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_8_1<-subset(PF,Grid=="R0.77"&Time=="1")
PF_8_2<-subset(PF,Grid=="R0.77"&Time=="2")
PF_8_3<-subset(PF,Grid=="R0.77"&Time=="3")
PF_8_4<-subset(PF,Grid=="R0.77"&Time=="4")
PF_8_5<-subset(PF,Grid=="R0.77"&Time=="5")
PF_8_6<-subset(PF,Grid=="R0.77"&Time=="6")
```
```{r,include=TRUE}
ggplot(PF_8_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_8_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_8_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_8_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_8_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_8_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.77 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_9_1<-subset(PF,Grid=="R0.72"&Time=="1")
PF_9_2<-subset(PF,Grid=="R0.72"&Time=="2")
PF_9_3<-subset(PF,Grid=="R0.72"&Time=="3")
PF_9_4<-subset(PF,Grid=="R0.72"&Time=="4")
PF_9_5<-subset(PF,Grid=="R0.72"&Time=="5")
PF_9_6<-subset(PF,Grid=="R0.72"&Time=="6")
```

```{r,include=TRUE}
ggplot(PF_9_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_9_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_9_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_9_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_9_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_9_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.72 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
#transform the data
PF$Abd_T= transformTukey(PF$Abd,plotit = FALSE)
PF_10_1<-subset(PF,Grid=="R0.6"&Time=="1")
PF_10_2<-subset(PF,Grid=="R0.6"&Time=="2")
PF_10_3<-subset(PF,Grid=="R0.6"&Time=="3")
PF_10_4<-subset(PF,Grid=="R0.6"&Time=="4")
PF_10_5<-subset(PF,Grid=="R0.6"&Time=="5")
PF_10_6<-subset(PF,Grid=="R0.6"&Time=="6")
```
```{r,include=TRUE}
ggplot(PF_10_1,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 1st sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_10_2,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 2nd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_10_3,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 3rd sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_10_4,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 4th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```
```{r,include=TRUE}
ggplot(PF_10_5,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 5th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```

```{r,include=TRUE}
ggplot(PF_10_6,aes(Xaxis,Yaxis,size=factor(Abd_T),color=factor(Abd_T)))+
  labs(title="Plant-feeding nematode in Grid 0.6 at 6th sampling time")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 60))+
  geom_point()+
  theme_bw()
```


```{r}
PF %>% 
  group_by(Grid) %>% 
  summarise(Abd = sum(Abd))

ggplot(PF,aes(Grid, Abd))+
  geom_bar(stat="identity")+
  theme_classic()

```







































